version: "3.8" 
volumes: 
    node_modules_server:
    node_modules_client:
    client_dist:
services:
    app:
        build: ./server/
        image: training-app
        volumes: 
            - ./server:/app
            - ./client/dist:/app/client
            - node_modules_server:/app/node_modules # this ensures that modules from windows will not be mounted into the container, but persisted in their own named vol
        ports:
            - 3000:3000
        command: "yarn prod"